name: scan_inv
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  barcode: ^2.2.9
  barcode_widget: ^2.0.4
  mobile_scanner: ^7.2.0
  file_picker: ^11.0.2
  csv: ^8.0.0
  excel: ^4.0.6
  sqflite: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
